name: presence_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  firebase_storage: ^10.2.12
  image_picker: ^0.8.5
  convex_bottom_bar: ^3.0.0
  intl: ^0.17.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  syncfusion_flutter_datepicker: ^20.1.52
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter: 
  uses-material-design: true

